import cozmo
def cozmo_program(robot: cozmo.robot.Robot):
    #robot.say_text("ah ee uh eh oh").wait_for_completed()
    #robot.say_text("car cki cuh cae coh").wait_for_completed()
    #robot.say_text("sar c thu saye sho").wait_for_completed()
	#robot.say_text("tar chee tue teh toh").wait_for_completed()
	#robot.say_text("ner nae nue neh noh").wait_for_completed()
	#robot.say_text("hah hee who heh hoh").wait_for_completed()
	#robot.say_text("mot me moo meh moh").wait_for_completed()
	#robot.say_text("yea you yoo").wait_for_completed()
	#robot.say_text("rar ree rhu reh rho").wait_for_completed()
	#robot.say_text("woa oh umm").wait_for_completed()
	#robot.say_text("gah git goh geh gho").wait_for_completed()
	#robot.say_text("zar g zoo zeh zoh").wait_for_completed()
	robot.say_text("dar g zoo deh doh").wait_for_completed()
	#robot.say_text("bar bee boh beh boh").wait_for_completed()
	#gggzzrobot.say_text("e pee poo peh poh").wait_for_completed()
	#robot.say_text("coh  nae chee woa,  woa tar c woa Cozmo dee thu.    yoo rho c cuh").wait_for_completed()

cozmo.run_program(cozmo_program)